language: python
python:
  - "2.7"

before install:
sudo apt-get install python-pip python2.7-dev libxext-dev python-qt4 qt4-dev-tools build-essential
# command to install dependencies
install : "pip install -r requirements.txt"

# run tests
script : 
