language: python
python:
  - "2.7"

# command to install dependencies
before_install:
 - sudo apt-get install python-numpy python-scipy python-sklearn
install : "sudo pip install -U -r requirements.txt"

# run tests
script : nosetests