language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -q python-numpy python-scipy python-sklearn libstdc++6
install : "sudo pip install -U -r requirements.txt"

# run tests
script : 
  - nosetests asla/binary/ml_tools/tests/test_predict_service.py
  - nosetests asla/binary/ml_tools/tests/test_training_service.py
  - nosetests asla/server/binary_server_backend/tests/test_ASLAController.py
  - nosetests asla/server/binary_server_backend/tests/test_global_model_service.py
  - nosetests asla/server/flask_website/tests/test_binary_helper.py
  - nosetests asla/server/flask_website/tests/test_FlaskWebsiteBackend.py
  - nosetests asla/server/flask_website/tests/test_user_admin_service.py

#notiifications management
notifications:
  email: false
  #slack:
    #on_failure: always
    #rooms: 
      #- ooseproject:12QWBnU53gpfpzaCJtYuDYSd#self
