language: python
python:
  - "2.7"

# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-sklearn
install : "sudo pip install -U -r requirements.txt"

# run tests
script : nosetests

#notiifications management
notifications:
  email: false
  slack:
    on_failure: always
    rooms: 
      - ooseproject:12QWBnU53gpfpzaCJtYuDYSd#self